### ISSUE TITLE
Flops of quantized model

### ISSUE THREAD

**Issue by cannguyen275** [1adrianb/pytorch-estimate-flops#7]
Hi,

Calculate Flops of a quantized model from https://github.com/pytorch/vision/blob/master/torchvision/models/quantization/mobilenetv2.py have this error:

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    count_ops(model, inp)
  File "/home/me/miniconda3/envs/env1/lib/python3.6/site-packages/pthflops/ops.py", line 291, in count_ops
    if next(model.parameters()).device != input_device:
StopIteration
```

**Comment by 1adrianb** [comment]
Hi @cannguyen275 can you clone and install from source please?

**Comment by 1adrianb** [comment]
This should also now be fixed on the pip package too.
